import 'package:get/get.dart';
import 'package:zoomato_app/Model/zoomatoModel.dart';

// ignore: camel_case_types
class Zoomato_controller extends GetxController {
  RxInt i = 0.obs;

  void change(int index) {
    i.value = index;
    update();
  }

 // ignore: non_constant_identifier_names
 List<Zoomato_Model> Foodlist = [
    Zoomato_Model(
      img: "assets/images/food/p1.png",
      time: "30-35",
      name: "Pizza",
      price: "150",
      price2: "200",
      price3: "440",
      price4: "300",
      price5: "200",
      disname: "La Pino'z Pizaa",
      disname2: "Domino's Pizza",
      disname3: "Pizza Hut",
      disname4: "Kutchi King",
      disname5: "Martion'z",
      img2: "assets/images/food/p2.jpeg",
      img3: "assets/images/food/p3.jpg",
      img4: "assets/images/food/p4.jpeg",
      img5: "assets/images/food/p5.jpeg",
      review: "4.0",
    ),
    Zoomato_Model(
      img: "assets/images/food/b1.png",
      time: "30-45",
      name: "Burger",
      price: "100",
      price2: "100",
      price3: "150",
      price4: "150",
      price5: "200",
      disname: "veg burger",
      disname2: "veg burger",
      disname3: "cheese burger",
      disname4: "bacon burger",
      disname5: "king burger",
      img2: "assets/images/food/b2.jpeg",
      img3: "assets/images/food/b3.jpeg",
      img4: "assets/images/food/b4.jpeg",
      img5: "assets/images/food/b5.jpeg",
      review: "4.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/c1.png",
      time: "20-35",
      name: "Cake",
      price: "300",
      price2: "450",
      price3: "600",
      price4: "250",
      price5: "550",
      disname: "Cheesecake",
      disname2: "Cheesecake",
      disname3: "Chocolate",
      disname4: "Fruit",
      disname5: "Vanilaa",
      img2: "assets/images/food/c2.jpeg",
      img3: "assets/images/food/c3.jpg",
      img4: "assets/images/food/c4.jpeg",
      img5: "assets/images/food/c5.jpeg",
      review: "3.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/s1.png",
      time: "20-30",
      name: "Sandwich",
      price: "100",
      price2: "100",
      price3: "180",
      price4: "190",
      price5: "120",
      disname: "Gangour",
      disname2: "Gangour",
      disname3: "Veggie House",
      disname4: "Grenee",
      disname5: "Laxmi Food Inn",
      img2: "assets/images/food/s2.jpeg",
      img3: "assets/images/food/s3.jpeg",
      img4: "assets/images/food/s4.jpeg",
      img5: "assets/images/food/s5.jpeg",
      review: "4.1",
    ),
    Zoomato_Model(
      img: "assets/images/food/d1.png",
      time: "30-35",
      name: "Dosa",
      price: "175",
      price2: "175",
      price3: "210",
      price4: "160",
      price5: "250",
      disname: "Dosa",
      disname2: "Masala ",
      disname3: "Cheese ",
      disname4: "Mysore ",
      disname5: "Plain",
      img2: "assets/images/food/d2.jpeg",
      img3: "assets/images/food/d3.jpeg",
      img4: "assets/images/food/d4.jpeg",
      img5: "assets/images/food/d5.jpeg",
      review: "4.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/ch1.png",
      time: "15-20",
      name: "Chinese",
      price: "100",
      price2: "180",
      price3: "210",
      price4: "100",
      price5: "180",
      disname: "Noodles",
      disname2: "Noodles",
      disname3: "Chinese Food",
      disname4: "Shrimp",
      disname5: "Manchurian",
      img2: "assets/images/food/ch2.jpeg",
      img3: "assets/images/food/ch3.jpeg",
      img4: "assets/images/food/ch4.jpeg",
      img5: "assets/images/food/ch5.jpeg",
      review: "3.7",
    ),
    Zoomato_Model(
      img: "assets/images/food/m1.png",
      time: "25-30",
      name: "Momos",
      price: "100",
      price2: "180",
      price3: "120",
      price4: "100",
      price5: "150",
      disname: "All",
      disname2: "Tandoori",
      disname3: "Vag",
      disname4: "Chicken",
      disname5: "panner",
      img2: "assets/images/food/m2.jpg",
      img3: "assets/images/food/m3.jpg",
      img4: "assets/images/food/m4.jpeg",
      img5: "assets/images/food/m5.jpeg",
      review: "3.3",
    ),
    Zoomato_Model(
      img: "assets/images/food/I1.png",
      time: "25-45",
      name: "Ice Cream",
      price: "70",
      price2: "120",
      price3: "70",
      price4: "100",
      price5: "150",
      disname: "Stawberry",
      disname2: "Stawberry",
      disname3: "Dessert",
      disname4: "Chocolate",
      disname5: "Cookies",
      img2: "assets/images/food/I2.jpeg",
      img3: "assets/images/food/I3.jpeg",
      img4: "assets/images/food/I4.jpeg",
      img5: "assets/images/food/I5.jpeg",
      review: "5.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/man.png",
      time: "20-35",
      name: "Manchurian",
      price: "180",
      price2: "180",
      price3: "280",
      price4: "190",
      price5: "150",
      disname: "dry Manchurian",
      disname2: "dry Manchurian",
      disname3: "Vag Manchurian",
      disname4: "Chinese",
      disname5: "paneer",
      img2: "assets/images/food/man2.jpeg",
      img3: "assets/images/food/man3.jpeg",
      img4: "assets/images/food/man4.jpg",
      img5: "assets/images/food/man5.jpg",
      review: "4.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/chaat1.png",
      time: "20-25",
      name: "Chaat",
      price: "10",
      price2: "20",
      price3: "50",
      price4: "60",
      price5: "80",
      disname: "Papdi",
      disname2: "Papdi",
      disname3: "Samosa",
      disname4: "Lahori",
      disname5: "papdi",
      img2: "assets/images/food/chaat2.jpeg",
      img3: "assets/images/food/chaat3.jpeg",
      img4: "assets/images/food/chaat4.jpeg",
      img5: "assets/images/food/chaat5.jpeg",
      review: "4.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/t1.png",
      time: "25-30",
      name: "Tacos",
      price: "165",
      price2: "165",
      price3: "190",
      price4: "110",
      price5: "150",
      disname: "asada",
      disname2: "asada",
      disname3: "beef",
      disname4: "stret",
      disname5: "ground beef",
      img2: "assets/images/food/t2.jpeg",
      img3: "assets/images/food/t3.jpeg",
      img4: "assets/images/food/t4.jpeg",
      img5: "assets/images/food/t5.jpeg",
      review: "4.3",
    ),
    Zoomato_Model(
      img: "assets/images/food/L1.png",
      time: "10-25",
      name: "Lassi",
      price: "120",
      price2: "120",
      price3: "200",
      price4: "170",
      price5: "250",
      disname: "Cocount",
      disname2: "Cocount",
      disname3: "Rose",
      disname4: "Mango",
      disname5: "Kesar",
      img2: "assets/images/food/L2.jpeg",
      img3: "assets/images/food/L3.jpeg",
      img4: "assets/images/food/L4.jpeg",
      img5: "assets/images/food/L5.jpeg",
      review: "4.4",
    ),
    Zoomato_Model(
      img: "assets/images/food/r1.png",
      time: "35-45",
      name: "Rasgulla",
      price: "100",
      price2: "140",
      price3: "120",
      price4: "200",
      price5: "150",
      disname: "Sweet",
      disname2: "Sweet",
      disname3: "Benguli",
      disname4: "Pink",
      disname5: "Sponge",
      img2: "assets/images/food/r2.jpeg",
      img3: "assets/images/food/r3.jpeg",
      img4: "assets/images/food/r4.jpeg",
      img5: "assets/images/food/r5.jpeg",
      review: "4.2",
    ),
    Zoomato_Model(
      img: "assets/images/food/pani1.png",
      time: "20-35",
      name: "Panipuri",
      price: "130",
      price2: "120",
      price3: "150",
      price4: "110",
      price5: "180",
      disname: "Masala",
      disname2: "Masala",
      disname3: "Sev puri",
      disname4: "Spicy",
      disname5: "Dahi",
      img2: "assets/images/food/pani2.jpeg",
      img3: "assets/images/food/pani3.jpeg",
      img4: "assets/images/food/pani4.jpeg",
      img5: "assets/images/food/pani5.jpeg",
      review: "7.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/sev1.png",
      time: "20-25",
      name: "Sev Poori",
      price: "100",
      price2: "90",
      price3: "120",
      price4: "180",
      price5: "190",
      disname: "Masala",
      disname2: "Masala",
      disname3: "Sev puri",
      disname4: "Spicy",
      disname5: "Dahi",
      img2: "assets/images/food/pani2.jpeg",
      img3: "assets/images/food/pani3.jpeg",
      img4: "assets/images/food/pani4.jpeg",
      img5: "assets/images/food/pani5.jpeg",
      review: "6.5",
    ),
    Zoomato_Model(
      img: "assets/images/food/bh1.png",
      time: "25-35",
      name: "Bhel",
      price: "150",
      price2: "100",
      price3: "150",
      price4: "80",
      price5: "120",
      disname: "Bhel",
      disname2: "Bhel puri",
      disname3: "Samosa",
      disname4: "Bhel samosa",
      disname5: "Kurkure",
      img2: "assets/images/food/bh2.jpeg",
      img3: "assets/images/food/bh3.jpeg",
      img4: "assets/images/food/bh4.jpeg",
      img5: "assets/images/food/bh5.jpeg",
      review: "4.4",
    ),
    Zoomato_Model(
      img: "assets/images/food/the1.png",
      time: "20-35",
      name: "Thepla",
      price: "100",
      price2: "150",
      price3: "240",
      price4: "250",
      price5: "180",
      disname: "Thepla",
      disname2: "Methi Thepla",
      disname3: "Dhudhi Thepla",
      disname4: "Methi Thepla",
      disname5: "Thepla",
      img2: "assets/images/food/the2.jpeg",
      img3: "assets/images/food/the3.jpeg",
      img4: "assets/images/food/the4.jpeg",
      img5: "assets/images/food/the5.jpeg",
      review: "4.4",
    ),
    Zoomato_Model(
      img: "assets/images/food/v1.png",
      time: "30-35",
      name: "Vada",
      price: "100",
      price2: "160",
      price3: "110",
      price4: "210",
      price5: "190",
      disname: "Medu Vada",
      disname2: "Medu Vada",
      disname3: "Chutney",
      disname4: "Spaicy",
      disname5: "Tiffin",
      img2: "assets/images/food/v2.jpeg",
      img3: "assets/images/food/v3.jpeg",
      img4: "assets/images/food/v4.jpeg",
      img5: "assets/images/food/v5.jpeg",
      review: "4.2",
    ),
    Zoomato_Model(
      img: "assets/images/food/dhabeli1.png",
      time: "20-35",
      name: "Dhabeli",
      price: "100",
      price2: "120",
      price3: "150",
      price4: "90",
      price5: "170",
      disname: "Mumbai",
      disname2: "Mumbai",
      disname3: "Kacci",
      disname4: "Kutchi",
      disname5: "cheese",
      img2: "assets/images/food/dhabeli2.jpeg",
      img3: "assets/images/food/dhabeli3.jpeg",
      img4: "assets/images/food/dhabeli4.jpeg",
      img5: "assets/images/food/dhabeli5.jpeg",
      review: "4.4",
    ),
  ];

  List<Zoomato_Model> cartlist =[];
  RxInt number = 0.obs;
  RxInt number2 = 0.obs;
  RxInt number3 = 0.obs;
  RxInt number4 = 0.obs;
}
